// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerInformRepository.EFDbContext
{
    public partial class Customers
    {
        public Guid custid { get; set; }
        public string custnm { get; set; }
        public string contactnum { get; set; }
        public string perosnalid { get; set; }
    }
}